ARG version
FROM almalinux:${version:-9}
ENV COURSE="DevOps" \
    DURATION="120HRS"
ARG TRAINER="Sivakumar"
RUN echo "Hi course is $COURSE, duration is $DURATION and trainer is $TRAINER"
CMD ["sleep", "1000"]
